// hsh_impl.h - Auto-Generated (Tue Jan 9 15:35:20 2018): Switch entries for the 'hsh' module. Include in the sm_get_entity() function switch statement, in your module source file.

case SM_GET_CITY_HASH: return (uint64_t)sm_load_entity(context, 1, city_hash_data, city_hash_size, &city_hash_key, &city_hash_crc);
case SM_GET_MURMUR_3_HASH: return (uint64_t)sm_load_entity(context, 1, murmur_3_hash_data, murmur_3_hash_size, &murmur_3_hash_key, &murmur_3_hash_crc);
case SM_GET_MURMUR_3_32_HASH: return (uint64_t)sm_load_entity(context, 1, murmur_3_32_hash_data, murmur_3_32_hash_size, &murmur_3_32_hash_key, &murmur_3_32_hash_crc);
case SM_GET_FNV1A_HASH: return (uint64_t)sm_load_entity(context, 1, fnv1a_hash_data, fnv1a_hash_size, &fnv1a_hash_key, &fnv1a_hash_crc);
case SM_GET_SHA_3_STATE: return sha_3_state;
case SM_GET_SHA_3_RESULT: return sha_3_result;
case SM_GET_SHA_3_KEYED: return sha_3_keyed;
case SM_GET_SHA_3_HASH: return (uint64_t)sm_load_entity(context, 1, sha_3_hash_data, sha_3_hash_size, &sha_3_hash_key, &sha_3_hash_crc);
case SM_GET_SIP_STATE: return sip_state;
case SM_GET_SIP_RESULT: return sip_result;
case SM_GET_SIP_KEYED: return sip_keyed;
case SM_GET_SIP_HASH: return (uint64_t)sm_load_entity(context, 1, sip_hash_data, sip_hash_size, &sip_hash_key, &sip_hash_crc);
case SM_GET_HIGHWAY_STATE: return highway_state;
case SM_GET_HIGHWAY_RESULT: return highway_result;
case SM_GET_HIGHWAY_KEYED: return highway_keyed;
case SM_GET_HIGHWAY_HASH: return (uint64_t)sm_load_entity(context, 1, highway_hash_data, highway_hash_size, &highway_hash_key, &highway_hash_crc);
case SM_GET_SPOOKY_128_STATE: return spooky_128_state;
case SM_GET_SPOOKY_128_RESULT: return spooky_128_result;
case SM_GET_SPOOKY_128_KEYED: return spooky_128_keyed;
case SM_GET_SPOOKY_128_HASH: return (uint64_t)sm_load_entity(context, 1, spooky_128_hash_data, spooky_128_hash_size, &spooky_128_hash_key, &spooky_128_hash_crc);
case SM_GET_SPOOKY_64_STATE: return spooky_64_state;
case SM_GET_SPOOKY_64_RESULT: return spooky_64_result;
case SM_GET_SPOOKY_64_KEYED: return spooky_64_keyed;
case SM_GET_SPOOKY_64_HASH: return (uint64_t)sm_load_entity(context, 1, spooky_64_hash_data, spooky_64_hash_size, &spooky_64_hash_key, &spooky_64_hash_crc);
case SM_GET_SPOOKY_32_STATE: return spooky_32_state;
case SM_GET_SPOOKY_32_RESULT: return spooky_32_result;
case SM_GET_SPOOKY_32_KEYED: return spooky_32_keyed;
case SM_GET_SPOOKY_32_HASH: return (uint64_t)sm_load_entity(context, 1, spooky_32_hash_data, spooky_32_hash_size, &spooky_32_hash_key, &spooky_32_hash_crc);
